# Generated by Django 5.2.15 on 2026-09-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fortytwo_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
