# Generated by Django 5.2.15 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_profile_avatar_and_friendship"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="forty_two_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
