# Generated by Django 5.2.15 on 2026-08-31
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_avatar_and_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='pair_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='generation',
            name='thread_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
    ]
